"""
Attribution Faithfulness Evaluator.
Evaluates LLM statements about feature importance, top-ranked predictors, and relative
influence against authoritative SHAP evidence.

CRITICAL METHODOLOGICAL DISTINCTION (Section 6):
Existing vector similarity metrics (Spearman rank correlation, cosine similarity, L1/L2 distance)
compare two numerical attribution vectors against each other. They are NOT natural-language
explanation-faithfulness metrics. This module specifically evaluates whether natural-language claims
generated by an LLM faithfully represent the ground-truth SHAP rankings and attributions.
"""
import re
from typing import List, Dict, Any, Optional, Set
from .taxonomy import ClaimType, ClaimClassification, ExtractedClaim, split_into_sentences
from ..evidence.schemas import AuditEvidence

MOST_IMPORTANT_PATTERNS = [
    r"most\s+(?:important|influential|significant|predictive|critical)\s+feature\s+(?:is|was|remains)?\s*[:]?\s*([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)(?:\.|\s+(?:in|for|of|to|with|having|and|governing|determining)|,|$)",
    r"([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)\s+(?:was|is)\s+the\s+most\s+(?:important|influential|significant|predictive|dominant)",
    r"top\s+predictor\s+(?:is|was)\s*[:]?\s*([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)(?:\.|\s+(?:in|for|of|to|with|having|and|governing|determining)|,|$)",
    r"highest\s+feature\s+importance\s+(?:belonged\s+to|was)?\s*[:]?\s*([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)(?:\.|\s+(?:in|for|of|to|with|having|and|governing|determining)|,|$)",
    r"([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)\s+had\s+the\s+largest\s+(?:impact|effect|shap\s+value)"
]

TOP_K_PATTERNS = [
    r"([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)\s+(?:was|is|ranked)\s+among\s+the\s+top\s+(?:features|predictors|variables)",
    r"([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)\s+(?:was|is)\s+one\s+of\s+the\s+top\s+(?:features|predictors|variables)",
    r"top\s+(?:features|predictors)\s+included?\s+([a-zA-Z0-9_]+(?:\s+[a-zA-Z0-9_]+)?)(?:\.|\s+(?:in|for|of|to|with|having|and)|,|$)"
]

RANK_EXPLICIT_PATTERNS = [
    r"([a-zA-Z0-9_\- ]+?)\s+(?:ranked|was\s+ranked|placed)\s+(?:#|number\s+)?(\d+)(?:st|nd|rd|th)?",
    r"(?:rank|#)\s*(\d+)\s+(?:was|is|feature\s+is)?\s*[:]?\s*([a-zA-Z0-9_\- ]+?)(?:\.|\s+with|,|$)"
]


class AttributionFaithfulnessEvaluator:
    """
    Evaluates statements regarding feature importance against authoritative SHAP rankings.
    """

    def __init__(self, top_k: int = 5):
        self.top_k = top_k

    def evaluate(self, evidence: AuditEvidence, text: str) -> List[ExtractedClaim]:
        claims: List[ExtractedClaim] = []

        # Ground truth SHAP from mitigated (if present) or baseline state
        active_state = evidence.mitigated_state or evidence.baseline_state
        if not active_state.shap_evidence or not active_state.shap_evidence.ranked_features:
            return claims

        shap_ev = active_state.shap_evidence
        ranked_features = shap_ev.ranked_features
        top_1_feature = ranked_features[0].feature_name if ranked_features else None
        top_shap_val = ranked_features[0].mean_abs_shap if ranked_features else 0.0

        # Account for tied SHAP values at rank 1
        tied_top_features = {
            f.feature_name for f in ranked_features
            if abs(f.mean_abs_shap - top_shap_val) <= 1e-6
        }

        top_k_features = set(shap_ev.top_k_features[:self.top_k])
        all_features = {f.feature_name for f in ranked_features}
        feature_rank_map = {f.feature_name: f.rank for f in ranked_features}
        state_label = "mitigated_state" if evidence.mitigated_state else "baseline_state"

        prov = {
            "experiment_id": evidence.experiment_id,
            "dataset": evidence.dataset.dataset_name if evidence.dataset else None,
            "model": evidence.model.model_family if evidence.model else None,
            "mitigation": evidence.model.mitigation_applied if evidence.model else None
        }
        ev_hash = getattr(evidence, "evidence_hash", None)

        sentences = split_into_sentences(text)
        claim_idx = 1

        for sent in sentences:
            # 1. Check for top-1 / most important feature claim
            matched_top1 = False
            for pattern in MOST_IMPORTANT_PATTERNS:
                m = re.search(pattern, sent, re.IGNORECASE)
                if m:
                    claimed_feature = m.group(1).strip()
                    matched_gt_name = self._resolve_feature_name(claimed_feature, all_features)

                    if matched_gt_name is None:
                        # Unrecognized feature name - classify as UNSUPPORTED
                        claims.append(ExtractedClaim(
                            claim_id=f"attr_top1_{claim_idx}",
                            experiment_id=evidence.experiment_id,
                            claim_type=ClaimType.ATTRIBUTION,
                            claim_text=sent,
                            ground_truth={
                                "true_top_1": top_1_feature,
                                "tied_top_1": list(tied_top_features),
                                "top_k": list(top_k_features)
                            },
                            predicted_claim={
                                "claimed_feature": claimed_feature,
                                "claim_role": "top_1_most_important"
                            },
                            classification=ClaimClassification.UNSUPPORTED,
                            rationale=f"Claimed feature '{claimed_feature}' does not exist in audited features.",
                            referenced_evidence=f"{state_label}.shap_evidence.ranked_features[0]",
                            extracted_values={"claimed_feature": claimed_feature, "claimed_role": "top_1"},
                            expected_values={"true_top_1": top_1_feature, "all_features": list(all_features)},
                            evidence_hash=ev_hash,
                            provenance=prov
                        ))
                        claim_idx += 1
                    else:
                        true_rank = feature_rank_map.get(matched_gt_name, 999)
                        is_top1 = (matched_gt_name in tied_top_features or true_rank == 1)
                        is_in_top_k = (true_rank <= self.top_k)

                        classification = (
                            ClaimClassification.SUPPORTED if is_top1
                            else (ClaimClassification.PARTIALLY_SUPPORTED if is_in_top_k else ClaimClassification.UNSUPPORTED)
                        )
                        rationale = (
                            f"Claimed top feature '{matched_gt_name}' is rank 1 (or tied top with mean |SHAP| {top_shap_val})."
                            if is_top1 else
                            f"Claimed top feature '{matched_gt_name}' is rank {true_rank} (true rank 1 is '{top_1_feature}')."
                        )

                        claims.append(ExtractedClaim(
                            claim_id=f"attr_top1_{claim_idx}",
                            experiment_id=evidence.experiment_id,
                            claim_type=ClaimType.ATTRIBUTION,
                            claim_text=sent,
                            ground_truth={
                                "true_top_1": top_1_feature,
                                "feature_rank": true_rank,
                                "top_k": list(top_k_features)
                            },
                            predicted_claim={
                                "claimed_feature": matched_gt_name,
                                "claim_role": "top_1_most_important"
                            },
                            classification=classification,
                            rationale=rationale,
                            referenced_evidence=f"{state_label}.shap_evidence.ranked_features[0]",
                            extracted_values={"claimed_feature": matched_gt_name, "claimed_role": "top_1"},
                            expected_values={"true_top_1": top_1_feature, "actual_rank": true_rank},
                            evidence_hash=ev_hash,
                            provenance=prov,
                            metadata={"rank": true_rank, "is_tied_top": (matched_gt_name in tied_top_features)}
                        ))
                        claim_idx += 1
                    matched_top1 = True
                    break

            if matched_top1:
                continue

            # 2. Check for explicit rank statements (e.g. "feature X ranked second", "ranked 3rd")
            matched_rank = False
            for pat in RANK_EXPLICIT_PATTERNS:
                rank_match = re.search(pat, sent, re.IGNORECASE)
                if rank_match:
                    # Depending on pattern, group 1 or group 2 might be the rank
                    g1, g2 = rank_match.group(1).strip(), rank_match.group(2).strip()
                    if g1.isdigit():
                        claimed_rank = int(g1)
                        claimed_feat = g2
                    else:
                        claimed_feat = g1
                        claimed_rank = int(g2)

                    matched_name = self._resolve_feature_name(claimed_feat, all_features)

                    if matched_name is not None:
                        actual_rank = feature_rank_map.get(matched_name)
                        is_correct_rank = (actual_rank == claimed_rank)
                        classification = ClaimClassification.SUPPORTED if is_correct_rank else ClaimClassification.UNSUPPORTED

                        claims.append(ExtractedClaim(
                            claim_id=f"attr_rank_{claim_idx}",
                            experiment_id=evidence.experiment_id,
                            claim_type=ClaimType.ATTRIBUTION,
                            claim_text=sent,
                            ground_truth={
                                "feature_name": matched_name,
                                "actual_rank": actual_rank
                            },
                            predicted_claim={
                                "feature_name": matched_name,
                                "claimed_rank": claimed_rank
                            },
                            classification=classification,
                            rationale=f"Claimed rank {claimed_rank} for '{matched_name}' (actual rank: {actual_rank}).",
                            referenced_evidence=f"{state_label}.shap_evidence.ranked_features",
                            extracted_values={"feature": matched_name, "claimed_rank": claimed_rank},
                            expected_values={"actual_rank": actual_rank},
                            evidence_hash=ev_hash,
                            provenance=prov
                        ))
                        claim_idx += 1
                        matched_rank = True
                        break
            if matched_rank:
                continue

            # 3. Check for top-k inclusion claims (e.g. "feature X was among the top predictors")
            for pattern in TOP_K_PATTERNS:
                m_topk = re.search(pattern, sent, re.IGNORECASE)
                if m_topk:
                    claimed_feat = m_topk.group(1).strip()
                    matched_name = self._resolve_feature_name(claimed_feat, all_features)
                    if matched_name is not None:
                        actual_rank = feature_rank_map.get(matched_name, 999)
                        is_top_k = (actual_rank <= self.top_k)
                        classification = ClaimClassification.SUPPORTED if is_top_k else ClaimClassification.UNSUPPORTED
                        rationale = (
                            f"Claim that '{matched_name}' is among top-{self.top_k} is supported (actual rank: {actual_rank})."
                            if is_top_k else
                            f"Claim that '{matched_name}' is among top-{self.top_k} is unsupported (actual rank: {actual_rank})."
                        )
                        claims.append(ExtractedClaim(
                            claim_id=f"attr_topk_{claim_idx}",
                            experiment_id=evidence.experiment_id,
                            claim_type=ClaimType.ATTRIBUTION,
                            claim_text=sent,
                            ground_truth={
                                "feature_name": matched_name,
                                "actual_rank": actual_rank,
                                "top_k_threshold": self.top_k
                            },
                            predicted_claim={
                                "feature_name": matched_name,
                                "claim_role": f"in_top_{self.top_k}"
                            },
                            classification=classification,
                            rationale=rationale,
                            referenced_evidence=f"{state_label}.shap_evidence.top_k_features",
                            extracted_values={"feature": matched_name, "claimed_role": f"in_top_{self.top_k}"},
                            expected_values={"actual_rank": actual_rank, "top_k_features": list(top_k_features)},
                            evidence_hash=ev_hash,
                            provenance=prov
                        ))
                        claim_idx += 1
                    break

        return claims

    def _resolve_feature_name(self, candidate: str, valid_features: Set[str]) -> Optional[str]:
        """
        Safely resolves feature name using exact normalized matching.
        Strips trailing grammatical particles (e.g. 'in', 'for', 'with').
        Does NOT perform arbitrary substring containment to prevent false positives
        (e.g. 'age' matching 'marriage').
        """
        cand = candidate.strip()
        words = cand.split()
        stopwords = {"in", "for", "of", "to", "with", "and", "as", "by", "from", "on", "at", "governing", "determining"}
        while len(words) > 1 and words[-1].lower() in stopwords:
            words.pop()
        cand = "_".join(words) if len(words) > 1 else (words[0] if words else "")

        cand_norm = cand.lower().strip().replace(" ", "_").replace("-", "_")
        for f in valid_features:
            f_norm = f.lower().strip().replace(" ", "_").replace("-", "_")
            if f_norm == cand_norm:
                return f
        return None
